from .newton import *
from .linearizado import *
from .sep import *
from .sistema import *
from .otimizacao import *
from .leitura import *
from .exportacao import *
from .latex import *
from .alternados import *
from .limites import *
from .exibir import *
from .modificar import *
from .compara import *
from .contingencia import *
from .logs import *
from .app import *
